config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/easy_login', to: 'sessions#easy_login'
  delete '/logout', to: 'sessions#destroy'
  
  get 'news/bbc'
  get 'news/wsj'
  get 'news/yahoo'
  get 'news/nhk'
  
  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :relationships, only:[:create, :destroy]
  resources :genres, only: :show
  resources :posts, only:[:index,:show,:new,:create,:destroy] do
    resources :comments, only:[:new, :create, :destroy]
    resources :likes, only:[:create, :destroy]
  end
  
end

app/views/shared/_comments_list.html.haml
.comments-for-post
  .comment-for-post
    .comment-upper
      .comment-upper__left
        = image_tag comment.user.picture.url
      .comment-upper__right
        .upper-right-top
          =link_to "#{comment.user.name}", user_path(comment.user)
          %p
            =comment.created_at
    .comment-bottom
      .comment-bottom-content
        =simple_format(comment.content)   

app/views/shared/_errors_messages.html.haml
- if @user.errors.any?
  #errors_list
    = pluralize(@user.errors.count, "error")
    %ul
      -@user.errors.full_messages.each do |error|
        %li 
          = error    

app/views/shared/_flash.html.haml
.flash
  - flash.each do |message_type, message|
    = content_tag(:div, message, class:message_type )

app/views/shared/_footer.html.haml
.footer 
  .footer__left
    %p Created by Nobuyuki Kanazawa
  .footer__right
    =link_to "Twitter", "#"

app/views/shared/_form.html.haml
.user-info
  .user-info__left
    -if current_user
      =render 'shared/left_side_bar'
  .user-info__center
    .input-page
      .input-form
        .input-form__title
          %h1 
            = yield(:title)
        .input-form__content
          -unless current_user 
            .easy-login
              =link_to "トップへ戻る", root_path 
              =link_to "お試しログインはこちら", easy_login_path, method: :post
          =form_with model:@user, local: true do |f|
            = render 'shared/user_errors_messages'
            .form-div.form-name
              =f.label :name
              =f.text_field :name,class:"text-field"
            .form-div.form-email
              =f.label :email
              =f.email_field :email,class:"text-field"
            .form-div.form-password
              =f.label :password
              =f.password_field :password,placeholder: "８文字以上",class:"text-field"
            .form-div.form-comfirmation
              =f.label :password_confirmation
              =f.password_field :password_confirmation,class:"text-field"
            .form-div.form-profile
              =f.label :profile
              =f.text_area :profile ,placeholder: "プロフィールを記入してください"
            .form-div.form-picture
              =f.label "picture (任意)"
              =f.file_field :picture, class: "file-field"
            .form-div.form-submit
              =f.submit "送信"   
            -if current_user && @user.admin != true
              .delete-btn
                =link_to "アカウント削除",user_path(@user), method: :delete, data:{confirm: "アカウントを削除しますか？"}

  .user-info__right
    -if current_user
      =render 'shared/right_side_bar'

app/views/shared/_header.html.haml
.header
  -if current_user 
    .display-btn
      %i{class:"fas fa-bars", id: "header-btn"}
    .user-links.page-links
      %h1 ページリンク
      =link_to "トップ", root_path
      =link_to "ユーザー一覧", users_path 
      =link_to "投稿する", new_post_path     
      =link_to "プロフィール編集", edit_user_path(current_user)
      =link_to "フォロー #{current_user.followings.count}",followings_user_path(current_user)
      =link_to "フォロワー #{current_user.followers.count}",followers_user_path(current_user)
      =link_to "マイページへ", user_path(current_user)
      =link_to "ログアウト", logout_path,{method: :delete}
    .genre-links.page-links
      %h1 ジャンルリンク
      =link_to "経済", genre_path(1)
      =link_to "ビジネス", genre_path(11)
      =link_to "政治", genre_path(21)
      =link_to "マネー", genre_path(31)
      =link_to "スポーツ", genre_path(41)
      =link_to "海外", genre_path(51)
      =link_to "その他", genre_path(61)
    .newssite-links.page-links
      %h1 ニュースリンク
      =link_to "BBC", news_bbc_path
      =link_to "WSJ", news_wsj_path
      =link_to "Yahoo!", news_yahoo_path
      =link_to "NHK", news_nhk_path

app/views/shared/_left_side_bar.html.haml
.links
  .links__title
    %h2 Links
  .links__options
    %ul.options-list
      %li
        =link_to "トップ", root_path
      %li
        =link_to "ユーザー一覧", users_path
      %li
        =link_to "投稿する", new_post_path
      %li
        =link_to "プロフィール編集", edit_user_path(current_user)
      %li
        =link_to "ログアウト", logout_path,{method: :delete}

.links
  .links__title
    %h2 Genres
  .links__options
    %ul.options-list
      %li
        =link_to "経済", genre_path(1)
      %li
        =link_to "ビジネス", genre_path(11)
      %li
        =link_to "政治", genre_path(21)
      %li
        =link_to "マネー", genre_path(31)
      %li
        =link_to "スポーツ", genre_path(41)
      %li
        =link_to "海外", genre_path(51)
      %li
        =link_to "その他", genre_path(61)

app/views/shared/_like_btn.html.haml
.like-display
  -if current_user.already_liked?(post)
    = form_with url: post_like_path(post, :id), method: :delete, remote: true do |f|
      = hidden_field_tag :user_id, current_user.id
      = button_tag type: 'submit' , class:"unlike-btn"  do
        = icon("fa", "heart")
    .like-count
      =post.likes.count
  -else
    = form_with scope: :like, url: post_likes_path(post), remote: true  do |f|
      = hidden_field_tag :user_id, current_user.id
      = button_tag type: 'submit' , class:"like-btn"  do
        = icon("far", "heart")
    .like-count
      =post.likes.count

app/views/shared/_post_errors_messages.html.haml
-if @post.errors.any?
  #errors_list
    = pluralize(@post.errors.count, "error")
    %ul
      -@post.errors.full_messages.each do |error|
        %li 
          = error

app/views/shared/_right_side_bar.html.haml
.user-data-links
  = render partial: 'shared/right_side_bar_follow'

.news-links
  .news-links__title
    %h2  News Links
  .news-link-btn.bbc
    =link_to "BBC", news_bbc_path
  .news-link-btn.wsj
    =link_to "WSJ", news_wsj_path
  .news-link-btn.yahoo
    =link_to "Yahoo!", news_yahoo_path
  .news-link-btn.nhk
    =link_to "NHK", news_nhk_path

app/views/shared/_right_side_bar_follow.html.haml
.user-data-links__title
  %h2 
    ="#{current_user.name}さん"
  .links__options
    %ul.option-list
      %li
        =link_to "フォロー #{current_user.followings.count}",followings_user_path(current_user)
      %li
        =link_to "フォロワー #{current_user.followers.count}",followers_user_path(current_user)
      %li
        =link_to "マイページへ", user_path(current_user)

app/views/shared/_user_errors_messages.html.haml
-if @user.errors.any?
  #errors_list
    = pluralize(@user.errors.count, "error")
    %ul
      -@user.errors.full_messages.each do |error|
        %li 
          = error

app/views/shared/_user_index_list.html.haml
.users-index
  =@url
  .users-index__left
    =render 'shared/left_side_bar'
    
  .users-index__center
    .user-contents
      .contents-title
        %h2 
          = yield(:title)
      .pagenation
        = paginate users
      -users.each do |user|
        .user-content
          .user-content-upper
            .user-content-upper__left
              .user-image
                =image_tag user.picture.url
            .user-content-upper__right
              .user-name
                =link_to "#{user.name}", user_path(user)
              .follow-unfollow-btn
                %div{id:"follow_btn_#{user.id}"}
                  =render 'shared/follow_btn',{ user: user}
          .user-content-bottom
            = simple_format user.profile
      .pagenation
        = paginate users

  .users-index__right
    =render 'shared/right_side_bar'

app/views/shared/_users_list.html.haml
.user-image
  = image_tag listed_user.picture.url
.user-name
  =link_to "#{listed_user.name}", user_path(listed_user)
.follow_unfollow_btn
  %div{id:"follow_btn_#{listed_user.id}"}
    =render 'shared/follow_btn',{ user: listed_user}