config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/easy_login', to: 'sessions#easy_login'
  delete '/logout', to: 'sessions#destroy'
  
  get 'news/bbc'
  get 'news/wsj'
  get 'news/yahoo'
  get 'news/nhk'
  
  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :relationships, only:[:create, :destroy]
  resources :genres, only: :show
  resources :posts, only:[:index,:show,:new,:create,:destroy] do
    resources :comments, only:[:new, :create, :destroy]
    resources :likes, only:[:create, :destroy]
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes,  dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :posts_genres_relationships,  dependent: :destroy
  has_many :genres, through: :posts_genres_relationships

  default_scope -> {order(created_at: :desc)} 
  validates :user_id, presence: true, allow_nil: true
  validates :content, presence: true, length:{maximum:140 }
  validates :url, presence: true, length: {maximum: 200}
  validates :posts_genres_relationship_ids, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except:[:index,:new,:create,:show, :destroy]
  before_action :check_login_user?,except: :index

  def index
    @user = current_user
    @posts = @user.feed.page(params[:page]).per(10).includes(:user, :genres) if user_login?
    @like = Like.new
  end
  
  def new
    @post =Post.new
    @genres = Genre.all
  end
  
  def create
    @post = Post.create(params_post)
    if @post.save
      flash[:succsess] = "投稿が完了しました"
      redirect_to root_path
    else
      flash.now[:alert] = "内容を確認してください"
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
    def params_post
      params.require(:post).permit(:content, :url, genre_ids:[]).merge(user_id: current_user.id)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def following_users_post(user)
    user.followings.each do |following|
      following.posts
    end
  end
end

app/views/posts/_post_list.html.haml
.user-post
  .user-post-upper
    .user-post-upper__left
      = image_tag post.user.picture.url
    .user-post-upper__right
      .post-right-top
        =link_to "#{post.user.name}", user_path(post.user)
        %p
          =post.created_at
      .post-right-bottom
        .post-bottom-item
          %p Genre：
          -post.genres.each do |genre|
            =link_to "#{genre.name}/",genre_path(genre)
        .post-bottom-item
          %p URL：
          =link_to "#{post.url}", post.url, target: :blank
  .user-post-bottom
    .post-bottom-content
      =simple_format(post.content)   
    .post-bottom-action
      =link_to  post_path(post) do
        .far.fa-comment-dots
        ="#{post.comments.count}"
      %div{id:"like-btn-#{post.id}"}
        =render partial: 'likes/like_btn',locals:{post: post}

app/views/posts/index.html.haml
=provide(:page_title, "TOP")
-if user_login?
  .user-info
    .user-info__left
      =render 'shared/left_side_bar'
    .user-info__center
      .show-contents.show
        .show-contents__title
          %h2
            トップ
        .user-posts
          = paginate @posts 
          -@posts.each do |post|
            =render 'shared/post_list',{post: post}
          = paginate @posts 

    .user-info__right
      =render 'shared/right_side_bar'
- else
  .top-page
    .top-page__top
      %h1 Output your reviews
      %p ニュースの学びにアウトプットを
      .top-links
        =link_to "ユーザ登録", new_user_path
        =link_to "ログイン", login_path
        =link_to "お試しログイン", easy_login_path, method: :post

    .top-page__center
      %h2 What you can do on this web site?
      .intro-contents
        .intro-contents__content
          .intro-title
            %h3 国内外のニュースサイトへアクセス！ 
          .intro-info
            %p BBC、WSJ、NHKなど、世界の主要ニュースサイトをピックアップ！広すぎず、狭すぎない、効果的なインプットを！
          .intro-images.intro-image-left
        .intro-contents__content
          .intro-title
            %h3 投稿機能で気になるニュースをシェア
          .intro-info
            %p ジャンル、URLとともにニュースをシェア。自分の意見を添えて、ニュースに関する考えをアウトプットしましょう！
          .intro-images.intro-image-center
        .intro-contents__content
          .intro-title
            %h3 その他機能の紹介(随時アップデート)
          .intro-info
            %p フォロー機能
            %p いいね機能
            %p 投稿へのコメント機能
          .intro-images.intro-image-right

app/views/posts/new.html.haml
.user-info
  .user-info__left
    =render 'shared/left_side_bar'
  .user-info__center
    .input-page
      .input-form
        .input-form__title
          %h1 新規投稿
        .input-form__content
          = form_with model: @post, local: true do |f|
            =render 'shared/post_errors_messages'
            .form-div
              =f.label "Genre"
              .form-checkbox
                =f.collection_check_boxes :genre_ids, Genre.all, :id, :name
            .form-div
              =f.label "Text"
              =f.text_area :content ,placeholder: "140文字以内"
            .form-div
              =f.label "URL"
              =f.text_field :url, placeholder: "サイトURLを記入してください"
            .form-div.form-submit
              = f.submit "Post"
    
  .user-info__right
    =render 'shared/right_side_bar'

app/views/posts/show.html.haml
.user-info
  .user-info__left
    =render 'shared/left_side_bar'
  .user-info__center
    .show-contents.show
      .comment-form
        =render template: "comments/new", locals:{post: @post, user: current_user}
      .user-posts
        =render 'shared/post_list',{post: @post}
      .user-reply
        .user-reply__title
          %h2
            コメント
        -@post.comments.each do |comment|
          =render 'shared/comments_list',{comment: comment}
        
  .user-info__right
    =render 'shared//right_side_bar_likes',locals:{ post: @post}